[build]
builder = "nixpacks"

[deploy]
startCommand = "python wsgi.py"
healthcheckPath = "/api/health/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
FLASK_ENV = "production"
