[build]
builder = "dockerfile"

[deploy]
startCommand = "python src/api/app.py"
healthcheckPath = "/api/health/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
FLASK_ENV = "production"
